name: pylops
channels:
  - defaults
  - conda-forge
  - numba
  - pytorch
dependencies:
  - python>=3.6.4
  - pip
  - numpy>=1.21.0,<2.0.0
  - scipy>=1.11.0
  - pytorch>=1.2.0
  - cpuonly
  - pyfftw
  - pywavelets
  - sympy
  - matplotlib
  - ipython
  - pytest
  - Sphinx
  - numpydoc
  - numba
  - icc_rt
  - pre-commit
  - autopep8
  - isort
  - black
  - pip:
    - devito
    - dtcwt
    - scikit-fmm
    - spgl1
    - pytest-runner
    - setuptools_scm
    - pydata-sphinx-theme
    - sphinx-gallery
    - nbsphinx
    - image
    - flake8
    - mypy
