name: pylops
channels:
  - defaults
  - conda-forge
  - numba
  - pytorch
dependencies:
  - python>=3.6.4
  - pip
  - mkl
  - mkl-fft
  - mkl-service
  - numpy>=1.21.0
  - scipy>=1.4.0
  - pytorch>=1.2.0
  - pyfftw
  - pywavelets
  - sympy
  - matplotlib
  - ipython
  - pytest
  - Sphinx
  - numpydoc
  - numba
  - icc_rt
  - pre-commit
  - autopep8
  - isort
  - black
  - nomkl
  - pip:
    - devito
    - scikit-fmm
    - spgl1
    - pytest-runner
    - setuptools_scm
    - sphinx-rtd-theme
    - sphinx-gallery
    - nbsphinx
    - image
    - flake8
    - mypy
